// Search quality on real docs: docusaurus.io's own, at a pinned commit (scripts/corpus.mjs), the
// corpus the 2026-10-10 audit measured. CI fetches it; locally, run `node scripts/corpus.mjs`
// first, or this file is skipped. The counts are snapshots: a change that loses a hit, or starts
// answering an off-topic query, fails here and has to say why.
import { existsSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { buildIndex, loadIndex } from '../src';
import { main } from '../src/cli/main';
import { loadDirectory, writeIndexFile } from '../src/node';
import { createMcpHandler } from '../src/server';

const corpus = join(
  process.env.ASK_MY_SITE_CORPUS ?? join(import.meta.dirname, '..', '.corpus'),
  'docusaurus',
);
const docs = join(corpus, 'website/docs');
const present = existsSync(docs);
if (!present && process.env.CI)
  throw new Error(`No corpus at ${docs}: run node scripts/corpus.mjs`);

/** A need as a person asks it, and as an agent searches for it, with the pages that answer it. */
const NEEDS: [question: string, query: string, pages: string[]][] = [
  [
    'How do I deploy my site to GitHub Pages?',
    'deploy GitHub Pages',
    ['/docs/deployment/github-pages', '/docs/deployment'],
  ],
  [
    'How can I generate a sidebar automatically from a folder?',
    'autogenerated sidebar from folder',
    ['/docs/sidebar/autogenerated'],
  ],
  [
    'How do I add a tip or warning callout box?',
    'admonitions tip warning',
    ['/docs/markdown-features/admonitions'],
  ],
  [
    'How do I highlight specific lines in a code block?',
    'code block highlight lines',
    ['/docs/markdown-features/code-blocks'],
  ],
  [
    'How do I add Algolia search to my site?',
    'Algolia DocSearch',
    ['/docs/search', '/docs/api/themes/@docusaurus/theme-search-algolia'],
  ],
  ['How do I version my documentation?', 'docs versioning', ['/docs/versioning']],
  [
    'How do I translate my site into French?',
    'i18n translate site',
    ['/docs/i18n/tutorial', '/docs/i18n/introduction'],
  ],
  [
    'How do I redirect old URLs to new pages?',
    'client redirects',
    ['/docs/api/plugins/@docusaurus/plugin-client-redirects'],
  ],
  ['How can I override a theme component?', 'swizzle theme component', ['/docs/swizzling']],
  [
    'How do I add Google Analytics?',
    'Google Analytics gtag',
    ['/docs/api/plugins/@docusaurus/plugin-google-gtag'],
  ],
  [
    'How do I render math equations with KaTeX?',
    'KaTeX math equations',
    ['/docs/markdown-features/math-equations'],
  ],
  [
    'How do I draw diagrams with Mermaid?',
    'mermaid diagrams',
    ['/docs/markdown-features/diagrams'],
  ],
  [
    'How do I show code samples for npm and yarn in tabs?',
    'tabs groupId npm yarn',
    ['/docs/markdown-features/tabs'],
  ],
  ["How do I change the site's primary color?", 'infima primary color', ['/docs/styling-layout']],
  [
    'Which browsers does my site support?',
    'browserslist browser support',
    ['/docs/browser-support'],
  ],
  ['How do I upgrade from v2 to v3?', 'migrate v2 to v3', ['/docs/migration/v3']],
  [
    'How do I customize the webpack config from a plugin?',
    'configureWebpack',
    ['/docs/api/plugin-methods/lifecycle-apis'],
  ],
  [
    'How do I serve images from the static folder?',
    'static folder images',
    ['/docs/static-assets'],
  ],
  ['How do I start the dev server on a different port?', 'docusaurus start --port', ['/docs/cli']],
  [
    'Can I write my config in TypeScript?',
    'docusaurus.config.ts TypeScript',
    ['/docs/typescript-support'],
  ],
  ['How do I host on Netlify?', 'Netlify deploy', ['/docs/deployment/netlify']],
  [
    'my build is slow, how can I make it faster?',
    'faster builds rspack',
    ['/docs/api/docusaurus-config'],
  ],
];

const OFF_TOPIC = [
  'What is the capital of France?',
  'How do I bake sourdough bread?',
  'How do I configure a Kubernetes ingress controller?',
  'Who won the 2022 World Cup?',
  'Write me a poem about the sea',
  'kubernetes ingress',
  'sourdough recipe',
  'django orm migrations',
];

describe.skipIf(!present)(
  'search on docusaurus.io’s docs (keyword-only, as with no embedding model)',
  async () => {
    const documents = present
      ? await loadDirectory(docs, { baseUrl: '/docs', framework: 'docusaurus' })
      : [];
    const { index } = await buildIndex({ documents });
    const loaded = loadIndex(index);
    const mcp = createMcpHandler({
      index: loaded,
      siteUrl: 'https://docusaurus.io',
      rateLimit: false,
    });
    let id = 0;
    const call = async (name: string, args: Record<string, unknown>) => {
      const response = await mcp(
        new Request('https://docusaurus.io/api/mcp', {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            accept: 'application/json, text/event-stream',
          },
          body: JSON.stringify({
            jsonrpc: '2.0',
            id: (id += 1),
            method: 'tools/call',
            params: { name, arguments: args },
          }),
        }),
      );
      const body = (await response.json()) as {
        result: { structuredContent: Record<string, unknown>; isError?: boolean };
      };
      return body.result;
    };
    const rank = async (query: string, pages: string[]): Promise<number> => {
      const { results } = (await call('search', { query })).structuredContent as {
        results: { id: string }[];
      };
      const found = [...new Set(results.map((result) => result.id.split('#')[0] ?? ''))];
      return found.findIndex((page) => pages.includes(page));
    };

    it('indexes every page', () => {
      expect([documents.length, index.chunks.length]).toEqual([92, 1070]);
    });

    it('finds the page an agent is looking for in the top three, for every query', async () => {
      const ranks = await Promise.all(NEEDS.map(([, query, pages]) => rank(query, pages)));
      const top = (k: number) => ranks.filter((r) => r >= 0 && r < k).length;
      expect({
        top1: top(1),
        top3: top(3),
        misses: NEEDS.filter((_, i) => (ranks[i] ?? -1) < 0 || (ranks[i] ?? 0) >= 3).map(
          ([, q]) => q,
        ),
      }).toEqual({
        top1: 19,
        top3: 22,
        misses: [],
      });
    });

    it('finds the page for most questions asked as a person asks them', async () => {
      const ranks = await Promise.all(NEEDS.map(([question, , pages]) => rank(question, pages)));
      expect(ranks.filter((r) => r >= 0 && r < 3).length).toBe(20);
    });

    it('returns nothing for off-topic queries', async () => {
      const counts = await Promise.all(
        OFF_TOPIC.map(async (query) => {
          const { results } = (await call('search', { query })).structuredContent as {
            results: unknown[];
          };
          return results.length;
        }),
      );
      expect(counts).toEqual(OFF_TOPIC.map(() => 0));
    });

    it('scores the sample eval file of the audit’s questions, as asked, within its thresholds', async () => {
      const dir = await mkdtemp(join(tmpdir(), 'ask-my-site-corpus-eval-'));
      try {
        await writeIndexFile(join(dir, 'ask-index.json'), index);
        const out: string[] = [];
        const code = await main(
          [
            'eval',
            join(import.meta.dirname, 'eval/docusaurus.io.yaml'),
            '--index',
            'ask-index.json',
            '--json',
          ],
          { cwd: dir, env: {}, stdout: (line) => out.push(line), stderr: () => undefined },
        );
        const { scores } = JSON.parse(out.join('\n')) as {
          scores: Record<string, { count: number; of: number }>;
        };
        expect(
          Object.fromEntries(
            Object.entries(scores).map(([name, { count, of }]) => [
              name,
              `${String(count)}/${String(of)}`,
            ]),
          ),
        ).toEqual({
          'hit@1': '14/22',
          'hit@3': '18/22',
          refusalPrecision: '6/8',
          refusalRecall: '6/6',
        });
        expect(code).toBe(0);
      } finally {
        await rm(dir, { recursive: true, force: true });
      }
    });

    it('fetches every page and every result, and lists them all', async () => {
      for (const document of documents) {
        const result = await call('fetch', { id: document.url });
        expect([document.url, result.isError ?? false]).toEqual([document.url, false]);
        expect((result.structuredContent.text as string).startsWith(`# ${document.title}`)).toBe(
          true,
        );
      }
      const { results } = (await call('search', { query: 'sidebar category index' }))
        .structuredContent as {
        results: { id: string; url: string }[];
      };
      for (const result of results) {
        const fetched = await call('fetch', { id: result.url });
        expect(fetched.structuredContent.url).toBe(result.url);
      }
      const list = await call('list_pages', {});
      expect(list.structuredContent.total).toBe(92);
    });
  },
);
