// Generated by scripts/sync-example-docs.mjs from the sections of examples/nextjs/content/docs.
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Get started',
      collapsible: false,
      items: ['introduction', 'getting-started', 'local-development'],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsible: false,
      items: ['docusaurus', 'astro', 'nextjs', 'script-tag', 'mcp', 'llms-txt'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: false,
      items: [
        'indexing',
        'model-providers',
        'deployment',
        'workers-ai',
        'security',
        'retrieval',
        'quality',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      items: [
        'api',
        'cli',
        'ask-endpoint',
        'ask-dialog',
        'index-format',
        'benchmarks',
        'limits',
        'faq',
        'migrating',
      ],
    },
  ],
};

export default sidebars;
