import { createAskHandler, memoryRateLimit } from 'ask-my-site/server';

import index from '../../../ask-index.json';
import {
  chatModel,
  embeddingModel,
  embeddingProviderOptions,
  minSimilarity,
} from '../../../lib/ai';

// `ask-index.json` is generated by `pnpm index`, which runs before `dev` and `build`.
export const POST = createAskHandler({
  index,
  model: chatModel,
  embeddingModel,
  ...(embeddingProviderOptions ? { embeddingProviderOptions } : {}),
  siteName: 'the ask-my-site docs',
  ...(minSimilarity ? { retrieval: { minSimilarity } } : {}),
  // Keyed by the last X-Forwarded-For entry, which Vercel sets. On Netlify, Cloudflare or Fly,
  // pass `trustedHeader` (see "Rate limits and client IPs" in the ask-my-site README).
  rateLimit: memoryRateLimit({ limit: 20, windowMs: 60_000 }),
});
