import { createAskHandler, memoryRateLimit } from 'ask-my-site/server';

import index from '../ask-index.json';
import { chatModel, embeddingModel, embeddingProviderOptions, minSimilarity } from './ai';

// `ask-index.json` is generated by `pnpm index`, which runs before `dev` and `build`.
export const askHandler = createAskHandler({
  index,
  model: chatModel,
  embeddingModel,
  ...(embeddingProviderOptions ? { embeddingProviderOptions } : {}),
  siteName: 'the ask-my-site docs',
  ...(minSimilarity ? { retrieval: { minSimilarity } } : {}),
  // Five questions a minute per visitor: in production every answer is a paid model call. A
  // token bucket, so a burst of five, then one more every 12 seconds. Keyed by the last
  // X-Forwarded-For entry, which Vercel sets, and by the /64 for IPv6. On Netlify, Cloudflare or
  // Fly, pass `trustedHeader` (see "Rate limits and client IPs" in the ask-my-site README).
  rateLimit: memoryRateLimit({ limit: 5, windowMs: 60_000 }),
  // A daily cap for the whole site, so rotating IPs cannot run up the bill: 300 questions and
  // 1M model tokens a day (an answer is about 3k). The counts live in memory, so each Vercel
  // instance has its own; the hard cap is the spend limit on the OpenAI project.
  budget: { requestsPerDay: 300, tokensPerDay: 1_000_000 },
  // The suggested questions are asked over and over: answer a repeat from memory, for free.
  answerCache: true,
});
