import { createAskHandler, memoryRateLimit } from 'ask-my-site/server';

import index from '../ask-index.json';
import { chatModel, embeddingModel, embeddingProviderOptions, minSimilarity } from './ai';

// `ask-index.json` is generated by `pnpm index`, which runs before `dev` and `build`.
export const askHandler = createAskHandler({
  index,
  model: chatModel,
  embeddingModel,
  ...(embeddingProviderOptions ? { embeddingProviderOptions } : {}),
  siteName: 'the ask-my-site docs',
  ...(minSimilarity ? { retrieval: { minSimilarity } } : {}),
  // Five questions a minute per visitor: in production every answer is a paid model call. A
  // token bucket, so a burst of five, then one more every 12 seconds. Keyed by the last
  // X-Forwarded-For entry, which Vercel sets. On Netlify, Cloudflare or Fly, pass
  // `trustedHeader` (see "Rate limits and client IPs" in the ask-my-site README).
  rateLimit: memoryRateLimit({ limit: 5, windowMs: 60_000 }),
});
